// ============================================================
// BLOG FORM - Create/Edit blog posts (No Supabase)
// ============================================================

import { showToast, loadList } from './content-loader.js';

export function renderForm() {
    return `
        <h2>Create New Blog Post</h2>
        <p class="form-subtitle">Write a new blog post for your audience.</p>

        <form id="blogForm" class="admin-form">
            <div class="form-group">
                <label for="blogTitle">Title *</label>
                <input type="text" id="blogTitle" class="form-input" placeholder="Enter blog post title" required />
            </div>

            <div class="form-group">
                <label for="blogSlug">Slug (URL)</label>
                <input type="text" id="blogSlug" class="form-input" placeholder="enter-blog-slug" />
                <span class="form-hint">Leave blank to auto-generate from title</span>
            </div>

            <div class="form-row">
                <div class="form-group">
                    <label for="blogCategory">Category</label>
                    <select id="blogCategory" class="form-select">
                        <option value="Content Strategy">Content Strategy</option>
                        <option value="AI Technology">AI Technology</option>
                        <option value="Social Media">Social Media</option>
                        <option value="Brand Building">Brand Building</option>
                        <option value="Growth">Growth</option>
                        <option value="Analytics">Analytics</option>
                        <option value="General">General</option>
                    </select>
                </div>
                <div class="form-group">
                    <label for="blogStatus">Status</label>
                    <select id="blogStatus" class="form-select">
                        <option value="draft">Draft</option>
                        <option value="published">Published</option>
                    </select>
                </div>
            </div>

            <div class="form-group">
                <label for="blogExcerpt">Excerpt (Summary)</label>
                <textarea id="blogExcerpt" class="form-textarea" rows="3" placeholder="Brief summary of the post..."></textarea>
            </div>

            <div class="form-group">
                <label for="blogContent">Content *</label>
                <textarea id="blogContent" class="form-textarea" rows="12" placeholder="Write your blog post content here..." required></textarea>
            </div>

            <div class="form-group">
                <label for="blogTags">Tags</label>
                <input type="text" id="blogTags" class="form-input" placeholder="AI, content, strategy (comma separated)" />
            </div>

            <div class="form-group">
                <label for="blogFeaturedImage">Featured Image URL</label>
                <input type="url" id="blogFeaturedImage" class="form-input" placeholder="https://example.com/image.jpg" />
            </div>

            <div class="form-row">
                <div class="form-group">
                    <label for="blogReadTime">Read Time (minutes)</label>
                    <input type="number" id="blogReadTime" class="form-input" value="5" min="1" />
                </div>
                <div class="form-group">
                    <label for="blogPublishDate">Publish Date</label>
                    <input type="datetime-local" id="blogPublishDate" class="form-input" />
                </div>
            </div>

            <button type="submit" class="btn-primary btn-full">Publish Blog Post</button>
        </form>
    `;
}

export function init() {
    const form = document.getElementById('blogForm');
    if (!form) return;

    // Auto-generate slug from title
    const titleInput = document.getElementById('blogTitle');
    const slugInput = document.getElementById('blogSlug');

    if (titleInput && slugInput) {
        titleInput.addEventListener('input', () => {
            if (!slugInput.value || slugInput.dataset.autoGenerated === 'true') {
                slugInput.value = titleInput.value
                    .toLowerCase()
                    .replace(/[^a-z0-9\s]/g, '')
                    .replace(/\s+/g, '-')
                    .trim();
                slugInput.dataset.autoGenerated = 'true';
            }
        });

        slugInput.addEventListener('input', () => {
            slugInput.dataset.autoGenerated = 'false';
        });
    }

    // Form submission
    form.addEventListener('submit', async (e) => {
        e.preventDefault();

        const btn = form.querySelector('button[type="submit"]');
        const originalText = btn.textContent;
        btn.textContent = 'Saving...';
        btn.disabled = true;

        try {
            // Collect form data
            const data = {
                title: document.getElementById('blogTitle').value,
                slug: document.getElementById('blogSlug').value || document.getElementById('blogTitle').value
                    .toLowerCase()
                    .replace(/[^a-z0-9\s]/g, '')
                    .replace(/\s+/g, '-')
                    .trim(),
                category: document.getElementById('blogCategory').value,
                excerpt: document.getElementById('blogExcerpt').value,
                content: document.getElementById('blogContent').value,
                tags: document.getElementById('blogTags').value.split(',').map(t => t.trim()).filter(Boolean),
                featured_image: document.getElementById('blogFeaturedImage').value,
                status: document.getElementById('blogStatus').value,
                read_time_minutes: parseInt(document.getElementById('blogReadTime').value) || 5,
                published_at: document.getElementById('blogPublishDate').value || new Date().toISOString(),
                created_at: new Date().toISOString()
            };

            console.log('Blog post saved (mock):', data);
            showToast('✅ Blog post published successfully!', 'success');
            form.reset();

            // Reload the list
            const event = new CustomEvent('content-saved', { detail: { type: 'blog' } });
            document.dispatchEvent(event);

        } catch (error) {
            console.error('Error saving blog:', error);
            showToast('❌ Error: ' + error.message, 'error');
        } finally {
            btn.textContent = originalText;
            btn.disabled = false;
        }
    });
}