// ============================================================
// PAGE FORM - Create/Edit static pages (No Supabase)
// ============================================================

import { showToast, loadList } from './content-loader.js';

export function renderForm() {
    return `
        <h2>Create New Page</h2>
        <p class="form-subtitle">Create a new static page for your website.</p>

        <form id="pageForm" class="admin-form">
            <div class="form-group">
                <label for="pageTitle">Page Title *</label>
                <input type="text" id="pageTitle" class="form-input" placeholder="Enter page title" required />
            </div>

            <div class="form-group">
                <label for="pageSlug">Slug (URL)</label>
                <input type="text" id="pageSlug" class="form-input" placeholder="page-url-slug" />
                <span class="form-hint">Leave blank to auto-generate from title</span>
            </div>

            <div class="form-row">
                <div class="form-group">
                    <label for="pageStatus">Status</label>
                    <select id="pageStatus" class="form-select">
                        <option value="draft">Draft</option>
                        <option value="published">Published</option>
                    </select>
                </div>
                <div class="form-group">
                    <label for="pageParent">Parent Page</label>
                    <select id="pageParent" class="form-select">
                        <option value="">None (Top Level)</option>
                        <option value="about">About</option>
                        <option value="services">Services</option>
                        <option value="blog">Blog</option>
                        <option value="pricing">Pricing</option>
                        <option value="contact">Contact</option>
                    </select>
                </div>
            </div>

            <div class="form-group">
                <label for="pageContent">Page Content *</label>
                <textarea id="pageContent" class="form-textarea" rows="12" placeholder="Write your page content here..." required></textarea>
            </div>

            <div class="form-group">
                <label for="pageMetaDescription">Meta Description (SEO)</label>
                <textarea id="pageMetaDescription" class="form-textarea" rows="2" placeholder="Brief description for search engines..."></textarea>
                <span class="form-hint">Recommended: 150-160 characters</span>
            </div>

            <div class="form-group">
                <label for="pageDisplayOrder">Display Order</label>
                <input type="number" id="pageDisplayOrder" class="form-input" value="0" min="0" />
                <span class="form-hint">Lower numbers appear first in navigation</span>
            </div>

            <button type="submit" class="btn-primary btn-full">Create Page</button>
        </form>
    `;
}

export function init() {
    const form = document.getElementById('pageForm');
    if (!form) return;

    // Auto-generate slug from title
    const titleInput = document.getElementById('pageTitle');
    const slugInput = document.getElementById('pageSlug');

    if (titleInput && slugInput) {
        titleInput.addEventListener('input', () => {
            if (!slugInput.value || slugInput.dataset.autoGenerated === 'true') {
                slugInput.value = titleInput.value
                    .toLowerCase()
                    .replace(/[^a-z0-9\s]/g, '')
                    .replace(/\s+/g, '-')
                    .trim();
                slugInput.dataset.autoGenerated = 'true';
            }
        });

        slugInput.addEventListener('input', () => {
            slugInput.dataset.autoGenerated = 'false';
        });
    }

    form.addEventListener('submit', async (e) => {
        e.preventDefault();

        const btn = form.querySelector('button[type="submit"]');
        const originalText = btn.textContent;
        btn.textContent = 'Creating...';
        btn.disabled = true;

        try {
            const slug = document.getElementById('pageSlug').value || document.getElementById('pageTitle').value
                .toLowerCase()
                .replace(/[^a-z0-9\s]/g, '')
                .replace(/\s+/g, '-')
                .trim();

            const data = {
                title: document.getElementById('pageTitle').value,
                slug: slug,
                status: document.getElementById('pageStatus').value,
                parent: document.getElementById('pageParent').value || null,
                content: document.getElementById('pageContent').value,
                meta_description: document.getElementById('pageMetaDescription').value,
                display_order: parseInt(document.getElementById('pageDisplayOrder').value) || 0,
                created_at: new Date().toISOString()
            };

            console.log('Page created (mock):', data);
            showToast('✅ Page created successfully!', 'success');
            form.reset();

            // Reload the list
            const event = new CustomEvent('content-saved', { detail: { type: 'page' } });
            document.dispatchEvent(event);

        } catch (error) {
            console.error('Error creating page:', error);
            showToast('❌ Error: ' + error.message, 'error');
        } finally {
            btn.textContent = originalText;
            btn.disabled = false;
        }
    });
}